name: Generate HTML and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake flex bison \
            libglib2.0-dev libcairo2-dev libpango1.0-dev \
            libxml2-dev libwebp-dev libzstd-dev \
            libgdk-pixbuf-2.0-dev time libreoffice

      - name: Install Ruby and gems
        run: |
          sudo apt-get install -y ruby-full
          echo 'gem: --no-document' | sudo tee /etc/gemrc

          sudo gem install asciidoctor nokogiri rghost asciidoctor-diagram \
                           asciidoctor-plantuml asciidoctor-pdf-cjk \
                           asciidoctor-lists coderay pygments.rb \
                           thread_safe slim concurrent-ruby \
                           haml tilt asciidoctor-mathematical \
                           asciidoctor-bibtex 
          sudo gem install asciidoctor-pdf -v 2.3.19
          sudo gem install asciidoctor-lists -v 1.1.2

          git clone https://github.com/rouge-ruby/rouge
          cd rouge
          gem build rouge.gemspec
          sudo gem install rouge-*.gem



      - name: Verify Installations
        run: |
          soffice --version
          asciidoctor --version
          asciidoctor-pdf --version

      - name: Generate HTML and PDF
        run: |
          cd docs/v1
          make

      - name: Deploy to GitHub Pages (Main Branch)
        if: ${{ github.event_name == 'push'}}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/v1/
          clean: true
