name: Generate HTML and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor libreoffice ruby  
          sudo apt install libpangocairo-1.0-0 libpango1.0-dev
          sudo apt-get install libwebp-dev libzstd-dev
          sudo gem install asciidoctor-pdf asciidoctor-mathematical asciidoctor-bibtex asciidoctor-lists

      - name: Verify Installations
        run: |
          soffice --version
          asciidoctor --version
          asciidoctor-pdf --version

      - name: Generate HTML and PDF
        run: |
          cd docs/v1
          make

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: p4runtime/docs/v1/_build/html  
          keep_files: false
