name: Generate HTML and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake flex bison \
            libglib2.0-dev libcairo2-dev libpango1.0-dev \
            libxml2-dev libwebp-dev libzstd-dev \
            libgdk-pixbuf-2.0-dev time libreoffice

      - name: Install Ruby and gems
        run: |
          sudo apt-get install -y ruby-full
          echo 'gem: --no-document' | sudo tee /etc/gemrc

          sudo gem install \
            asciidoctor nokogiri rghost \
            asciidoctor-diagram asciidoctor-plantuml \
            asciidoctor-pdf -v 2.3.19 asciidoctor-pdf-cjk \
            asciidoctor-lists -v 1.1.2 \
            coderay pygments.rb thread_safe slim \
            concurrent-ruby haml tilt \
            asciidoctor-mathematical asciidoctor-bibtex 


          git clone https://github.com/rouge-ruby/rouge
          cd rouge
          gem build rouge.gemspec
          sudo gem install rouge-*.gem



      - name: Verify Installations
        run: |
          soffice --version
          asciidoctor --version
          asciidoctor-pdf --version

      - name: Generate HTML and PDF
        run: |
          cd docs/v1
          make

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: p4runtime/docs/v1  
          keep_files: false
